[package]
name = "streams-tools"
version = "0.1.2"
edition = "2018"
license = "Apache-2.0/MIT"
keywords = ["iota", "streams"]
description = "Tools to facilitate usage of iota streams"

[lib]
name = "streams_tools"
crate-type = ["rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iota-streams = { git = "https://github.com/iotaledger/streams", branch = "develop", default-features = false, features = ["std", "tangle"] }
futures = { version = "0.3.8", default-features = false, features = ["executor"] }
anyhow = "1.0.40"
rand = "0.7.3"
url = "2.2.2"
hyper = { version = "0.14", features = ["client", "http1"] }
iota-client-types = { version = "0.1.2", path = "../iota-client-types" }

# smol_rt dependencies
smol = { version = "1.2", optional = true }

# esp_idf dependencies
esp-idf-svc = { version = "0.39.1", optional = true }
esp-idf-sys = { version = "0.31.0", optional = true }
# esp-idf-hal = { version = "0.33.1", optional = true }
embedded-svc = { version = "0.19", optional = true }
# embedded-hal = { version = "0.2", optional = true }

# std dependencies
tokio = { version = "1.5", optional = true }


[features]
default = ["std"]
smol_rt = ["smol"]
esp_idf = ["embedded-svc", "esp-idf-svc", "esp-idf-sys"] # , "esp-idf-hal", "embedded-hal"
std = ["tokio", "iota-streams/client", "iota-streams/std"]