[workspace]
members = [
    "management-console",
    "sensor",
    "tangle-proxy",
    "streams-tools",
    "susee-tools",
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true
#panic = 'abort'