[workspace]
members = [
    "management-console",
    "sensor/main-rust",
    "sensor/main-rust-esp-r",
    "sensor/main-rust-pio",
    "sensor/sensor-lib",
    "iota-client-types",
    "tangle-proxy",
    "streams-tools",
    "susee-tools",
    "test/payloads",
]

exclude = [
    "sensor/main-idf/components/rustlib",
]

resolver = "2"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"



[patch.crates-io]
socket2 = { git = "https://github.com/esp-rs-compat/socket2" }
# getrandom1 = { version = "0.1.16", git = "https://github.com/rust-random/getrandom.git", package = "getrandom", tag = "v0.1.16" }
getrandom1 = { version = "0.1", path = "../getrandom", package = "getrandom"}
getrandom = { version = "0.2", git = "https://github.com/rust-random/getrandom.git" }
smol = { git = "https://github.com/esp-rs-compat/smol" }
polling = { git = "https://github.com/esp-rs-compat/polling" }
esp-idf-svc = { version = "0.39.1", path = "../../esp-rs/esp-idf-svc/" }
# esp-idf-sys = { version = "0.31.0", path = "../../esp-rs/esp-idf-sys/" }
esp-idf-sys = { version = "0.31.0", git = "https://github.com/esp-rs/esp-idf-sys.git", rev = "b33f72191701b245f3129f81b2120fac78876694" }
time = { version = "=0.3.4", git = "https://github.com/time-rs/time", rev="8ec5f4ef2f63321b3dbbec3b4a6c4001fdf26de6" }
iota-crypto = { version = "0.9.1", git = "https://github.com/iotaledger/crypto.rs.git", rev="6840d43f98ad1a991571268f7a9543025200ca4f" }

#[patch."https://github.com/iotaledger/streams"]
#iota-streams = { version = "0.1.2", path = "../../iotaledger/streams" }

# [patch."https://github.com/iotaledger/crypto.rs"]
# iota-crypto = { version = "0.9.1", git = "https://github.com/iotaledger//crypto.rs.git", rev="6840d43f98ad1a991571268f7a9543025200ca4f" }
