[workspace]
members = [
    "management-console",
    "sensor/main-rust",
    "sensor/main-rust-esp-r",
    "sensor/main-rust-pio",
    "sensor/sensor-lib",
    "iota-client-types",
    "tangle-proxy",
    "streams-tools",
    "susee-tools",
]

exclude = [
    "sensor/main-idf/components/rustlib",
]

resolver = "2"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"



[patch.crates-io]
# socket2 = { git = "https://github.com/esp-rs-compat/socket2" }
# getrandom1 = { version = "0.1.16", git = "https://github.com/rust-random/getrandom.git", package = "getrandom", tag = "v0.1.16" }
# getrandom1 = { version = "0.1", path = "../getrandom", package = "getrandom"}
# getrandom = { version = "0.2", git = "https://github.com/rust-random/getrandom.git" }
# smol = { git = "https://github.com/esp-rs-compat/smol" }
# polling = { git = "https://github.com/esp-rs-compat/polling" }

[patch."https://github.com/iotaledger/streams"]
iota-streams = { version = "0.1.2", path = "../../iotaledger/streams" }
